# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run an ML Pipeline

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.TAG_NAME}} 
    steps:
      - uses: actions/checkout@v2
      - name: repo_branch
      - id: step1
        env:
          repo_token: ${{secrets.GITHUB_TOKEN}}
        run: |
          sudo bash ./script.sh
          
  job2:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    needs: job1
    steps:
      - name: cml_run
        env:
          repo_token: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo ${{needs.job1.outputs.output1}}
          pip install -r requirements.txt
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md master > report.md

          cml-publish by_region.png --md >report.md
          cml-send-comment report.md
